name = "Gallery"
license = "MIT"
licenselink = "https://github.com/cmonr/hugo-theme-gallery/blob/main/LICENSE"
description = "A simple photo gallery theme for Hugo"
homepage = "https://github.com/cmonr/hugo-theme-gallery"
demosite = "https://cmonr.github.io/from-the-workbench/"
tags = ["gallery", "responsive", "minimal", "light"]
min_version = "0.123.0"

[author]
  name = "Cruz Monrrea iI"
